### ISSUE TITLE
It creates two windows

### ISSUE THREAD

**Issue by m1cl** [TanvirMahin24/winbox-react#1]
I created a react app with "creact-react-app".  Somehow in renders two windows. 

```
function App() {
  return (
    <div className="App">
      <WinBox title={"HELLO"}></WinBox>
    </div>
  );
}
```

**Comment by TanvirMahin24** [comment]
```jsx
<React.StrictMode>
    <App />
  </React.StrictMode>
```
Please remove this <React.StrictMode> in the index.js file in the src directory. I hope this would solve your issue.
