### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by ghost** [TanvirMahin24/winbox-react#2]
I am using in Next.js and get this error. Could you share how to fix it?
```
./node_modules/winbox-react/node_modules/winbox/dist/css/winbox.min.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/winbox-react/dist/index.modern.js
```
Thank you so much.

**Comment by TanvirMahin24** [comment]
Have you tried reinstalling the package and see if the problem is solved? Let me know if you still have this problem.

**Comment by ghost** [comment]
> Have you tried reinstalling the package and see if the problem is solved? Let me know if you still have this problem.

Yes. I have been reinstalling and still get it error.
Everytime I import ```import WinboxReact from "winbox-react";```, the error will appear.

I'm using Next.js 10.2.3

**Comment by TanvirMahin24** [comment]
Can you please go to this directory "node_modules/winbox-react/node_modules/winbox/dist/css/winbox.min.css" and check manually if this file exists or not?

**Comment by ghost** [comment]
<img width="209" alt="Screen Shot 2021-05-31 at 17 31 27" src="https://user-images.githubusercontent.com/18575253/120180507-0900c500-c236-11eb-9e2e-dc79b887891b.png">

Yes. It exists.

**Comment by TanvirMahin24** [comment]
I could not find any solution. Please use the winbox js package.
