### ISSUE TITLE
React inside windows

### ISSUE THREAD

**Issue by alegjd** [TanvirMahin24/winbox-react#5]
Hi!
thanks for the package, it's awesome.
I do have a pretty big problem, though.
It seems like I can't use React components inside a window?
Is there a way to do so?
Thanks!

**Comment by RickoNoNo3** [comment]
This library just creates the window and renders its children once to static. No lifecycle maintained. So I have to reproduce another one (and I'm so sorry about the two projects are too different to be merged together ). I implemented the full lifecycle of a window, including the dynamic management such as size changing, position changing, focus, etc... see [here](https://github.com/rickonono3/react-winbox)

**Comment by TanvirMahin24** [comment]
Thanks, @RickoNoNo3. Loved your package and best of luck ❤
